"""Generate "The Placement Premium, Measured" from trace JSONLs.

Turns P0 output into the launch asset automatically: per-silicon calibration
table (fits + 95% CIs + holdout MAPE), validation verdict summary, and
premium tables for reference workload shapes computed from the CALIBRATED
fleet at reference prices. Deliberately mechanical — the report's authority
comes from being generated by the same audited code that made the claims.

Usage:
    python -m bench.report traces1.jsonl traces2.jsonl ... --out REPORT.md
    python -m bench.report --rehearsal --out REPORT.md   # mock dress run
"""

import argparse

from bench.sounding import load_jsonl
from bench.validate import check_bandwidth, check_kv_slope, check_prefill
from berth import FLEET, MODELS, PlacementClient, SimBackend, WorkloadSpec, calibrate

REFERENCE_SHAPES = {
    "chat (1k/256, b16, p99 TTFT<500ms, 40 rps)": dict(
        model="llama3-70b", avg_prompt_tokens=1024, avg_output_tokens=256,
        target_batch=16, p99_ttft_ms=500.0, arrival_rps=40.0),
    "RAG long-context (8k/512, b8)": dict(
        model="llama3-70b", avg_prompt_tokens=8192, avg_output_tokens=512,
        target_batch=8),
    "small-model streaming (0.5k/128, b4, p99 TTFT<200ms, 60 rps)": dict(
        model="llama3-8b", avg_prompt_tokens=512, avg_output_tokens=128,
        target_batch=4, p99_ttft_ms=200.0, arrival_rps=60.0),
}


def premium_table(fleet) -> str:
    lines = []
    client = PlacementClient(SimBackend(seed=0, fleet=fleet))
    for label, kw in REFERENCE_SHAPES.items():
        kw = dict(kw)
        sig = client.profile(WorkloadSpec(model=MODELS[kw.pop("model")], **kw))
        lines.append(f"\n### {label}\n")
        lines.append("| silicon | $/Mtok | premium | note |")
        lines.append("|---|---|---|---|")
        for e in client.estimate(sig):
            if e.feasible:
                note = f"{e.bound}-bound" + (f", {e.replicas} replicas" if e.replicas > 1 else "")
                lines.append(f"| {e.silicon} | {e.cost_per_mtok:.2f} "
                             f"| {e.placement_premium:.0%} | {note} |")
            else:
                lines.append(f"| {e.silicon} | — | — | infeasible: {e.reason} |")
    return "\n".join(lines)


def build_report(traces, rehearsal: bool) -> str:
    fleet, rep = calibrate(FLEET, traces)
    # Physics checks against the FITTED fleet: they verify model form;
    # parameter offsets are calibration's job (see bench/validate.py).
    checks = (check_bandwidth(traces, fleet) + check_kv_slope(traces, fleet)
              + check_prefill(traces, fleet))
    verdicts = [str(v) for _, _, v in checks]
    n_pass = sum(v == "PASS" for v in verdicts)
    n_fail = sum(v.startswith("FAIL") for v in verdicts)
    n_skip = len(verdicts) - n_pass - n_fail

    out = []
    out.append("# The Placement Premium, Measured")
    if rehearsal:
        out.append("\n> **REHEARSAL — SYNTHETIC DATA.** This report was generated "
                   "from the mock harness to validate the pipeline. No number "
                   "below is a hardware measurement. Do not publish.")
    out.append(f"\nTraces: {len(traces)} · Holdout MAPE: prior "
               f"{rep.mape_prior:.1%} → calibrated {rep.mape_calibrated:.1%} · "
               f"Physics checks: {n_pass} PASS / {n_fail} FAIL / {n_skip} SKIP")

    # Provenance: name the quant mix. A premium computed across cells at
    # different precisions is not apples-to-apples unless the reader is told.
    from collections import Counter
    quant_mix = Counter(
        MODELS[t.model_name].quantized(t.w_bytes, t.kv_bytes).quant_label
        for t in traces if t.model_name in MODELS
    )
    if len(quant_mix) > 1 or (quant_mix and "w:bf16/kv:bf16" not in quant_mix):
        mix = " · ".join(f"{lbl}: {n}" for lbl, n in quant_mix.most_common())
        out.append(f"\n> **Quant mix (not all bf16):** {mix}. "
                   "Premiums mix precisions; compare within a precision.")

    out.append("\n## Calibrated efficiency factors (95% bootstrap CIs)\n")
    out.append("| silicon | n | mfu [CI] | bw_eff [CI] |")
    out.append("|---|---|---|---|")
    for name in FLEET:
        n = rep.n_traces.get(name, 0)
        if n == 0 or name not in rep.ci95:
            out.append(f"| {name} | 0 | prior (unmeasured) | prior (unmeasured) |")
            continue
        mfu, bw = rep.fitted[name]
        (ml, mh), (bl, bh) = rep.ci95[name]
        out.append(f"| {name} | {n} | {mfu:.3f} [{ml:.3f}, {mh:.3f}] "
                   f"| {bw:.3f} [{bl:.3f}, {bh:.3f}] |")

    out.append("\n## Placement premiums at reference workload shapes")
    out.append("*(calibrated fleet, reference on-demand prices; premium = "
               "cost vs best feasible placement)*")
    out.append(premium_table(fleet))

    out.append("\n## Method\nAnalytical roofline (closed-form, "
               "hand-derivable) + inversion calibration with robust medians; "
               "term-by-term physics validation with identifiability gates; "
               "raw traces and harness are in this repository. "
               "Disputes: attach traces (see CONTRIBUTING).")
    return "\n".join(out) + "\n"


def _rehearsal_traces():
    """Mock traces across the fleet with perturbed hidden truths, so the
    rehearsal exercises calibration actually moving numbers.

    The fixture pins its own model set: it is a synthetic-truth dress rehearsal
    of the pipeline, NOT a registry sweep. Decoupling it from the live MODELS
    dict keeps the zero-FAIL gate deterministic — otherwise every new model
    added to MODELS reshuffles generate_traces' seeded rng.choice() stream and
    can flip a sparse high-batch KV-slope cell (artifact, not a physics defect).
    Real models are validated on MEASURED traces, not this fixture."""
    from berth import MODELS, generate_traces, make_true_fleet
    reference_models = {k: MODELS[k] for k in ("llama3-8b", "llama3-70b", "qwen3-235b-moe")}
    true_eff = {n: (max(0.1, hw.mfu * 0.92), max(0.1, hw.bw_eff * 1.06))
                for n, hw in FLEET.items()}
    return generate_traces(make_true_fleet(FLEET, true_eff), models=reference_models,
                           n_per_silicon=90, noise_sigma=0.05, seed=17)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("files", nargs="*")
    p.add_argument("--rehearsal", action="store_true")
    p.add_argument("--out", default="REPORT.md")
    args = p.parse_args()
    if args.rehearsal:
        traces = _rehearsal_traces()
    elif args.files:
        traces = [t for f in args.files for t in load_jsonl(f)]
    else:
        p.error("provide trace files or --rehearsal")
    open(args.out, "w").write(build_report(traces, args.rehearsal))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
